# Generated by Django 3.2 on 2022-12-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.CharField(db_column='classID', max_length=20, primary_key=True, serialize=False)),
                ('classcode', models.CharField(blank=True, db_column='classCode', max_length=45, null=True)),
                ('classname', models.CharField(blank=True, db_column='className', max_length=45, null=True)),
                ('classschoolyear', models.CharField(blank=True, db_column='classSchoolYear', max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='usrclass',
            field=models.ForeignKey(blank=True, db_column='usrclass', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.class'),
        ),
    ]
