# Generated by Django 3.2 on 2022-12-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0002_auto_20221201_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
        migrations.RunSQL("INSERT INTO `class` (`classID`, `classCode`, `className`, `classSchoolYear`) VALUES ('1', 'KHMT001', 'Khoa học máy tính K57', '2020-2021');")
    ]
