# Generated by Django 3.2.2 on 2022-12-19 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0003_alter_results_resulttestingdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='expcreatorid',
            field=models.ForeignKey(blank=True, db_column='expCreatorID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='expdatasetid',
            field=models.ForeignKey(blank=True, db_column='expDatasetID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expAI.datasets'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='expmodelid',
            field=models.ForeignKey(blank=True, db_column='expModelID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expAI.models'),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='expsoftwarelibid',
            field=models.ForeignKey(blank=True, db_column='expSoftwareLibID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.softwarelibs'),
        ),
        migrations.AlterField(
            model_name='paramsconfigs',
            name='configevaluateid',
            field=models.ForeignKey(blank=True, db_column='configEvaluateID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.evaluations'),
        ),
        migrations.AlterField(
            model_name='paramsconfigs',
            name='configexpid',
            field=models.ForeignKey(blank=True, db_column='configExpID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.experiments'),
        ),
        migrations.AlterField(
            model_name='results',
            name='resultconfigid',
            field=models.ForeignKey(blank=True, db_column='resultConfigID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.paramsconfigs'),
        ),
        migrations.AlterField(
            model_name='results',
            name='resulttestingdataset',
            field=models.ForeignKey(blank=True, db_column='resultTestingDataset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expAI.datasets'),
        ),
        migrations.AlterField(
            model_name='trainningresults',
            name='configid',
            field=models.ForeignKey(blank=True, db_column='configID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.paramsconfigs'),
        ),
    ]
