# Generated by Django 3.2 on 2022-12-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0004_auto_20221201_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problemid', models.AutoField(primary_key=True, serialize=False)),
                ('problemname', models.CharField(blank=True, db_column='problemName', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Problem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypePermission',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(blank=True, db_column='typeName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'TypePermission',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='datasets',
            name='datasetproblem',
            field=models.ForeignKey(blank=True, db_column='datasetProblem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.problem'),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='datasettype',
            field=models.ForeignKey(blank=True, db_column='datasetType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.typepermission'),
        ),
        migrations.RunSQL("INSERT INTO `typepermission` (`typeid`, `typeName`) VALUES ('1', 'PUBLIC');"),
        migrations.RunSQL("INSERT INTO `typepermission` (`typeid`, `typeName`) VALUES ('0', 'PRIVATE');"),

        migrations.RunSQL("INSERT INTO `problem` (`problemid`, `problemName`) VALUES ('1', 'FACE_RECOG');"),
        migrations.RunSQL("INSERT INTO `problem` (`problemid`, `problemName`) VALUES ('2', 'FACE_DETECT');"),
        migrations.RunSQL("INSERT INTO `problem` (`problemid`, `problemName`) VALUES ('0', 'ACTION_ABNORMAL');"),
    ]
