# Generated by Django 3.2.2 on 2022-12-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0005_auto_20221201_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasets',
            name='datasetproblem',
        ),
        migrations.AddField(
            model_name='datasets',
            name='expsoftwarelibid',
            field=models.ForeignKey(blank=True, db_column='expSoftwareLibID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.softwarelibs'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
