# Generated by Django 3.2.2 on 2022-12-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0006_auto_20221202_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsconfigs',
            name='jsonstringparams',
            field=models.CharField(blank=True, db_column='jsonStringParams', max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='paramsconfigs',
            name='trainningstatus',
            field=models.IntegerField(db_column='trainningstatus', default=1),
        ),
    ]
