# Generated by Django 3.2 on 2022-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0006_auto_20221204_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='datasetdescription',
            field=models.CharField(blank=True   , db_column='datasetDescription', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='datasetid',
            field=models.AutoField(db_column='datasetID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiments',
            name='expname',
            field=models.CharField(blank=True   , db_column='expName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='objgeneralinfo',
            field=models.CharField(blank=True   , db_column='objGeneralInfo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='objname',
            field=models.CharField(blank=True   , db_column='objName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrfullname',
            field=models.CharField(blank=True   , db_column='usrFullName', max_length=50, null=True),
        ),
    ]
