# Generated by Django 3.2.2 on 2022-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0007_auto_20221203_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='expid',
            field=models.AutoField(db_column='expID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paramsconfigs',
            name='configid',
            field=models.AutoField(db_column='configID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results',
            name='resultid',
            field=models.AutoField(db_column='resultID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
