# Generated by Django 3.2.2 on 2022-12-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0010_remove_experiments_exptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasets',
            name='datasettesting',
        ),
        migrations.RemoveField(
            model_name='datasets',
            name='datasettraining',
        ),
        migrations.AddField(
            model_name='models',
            name='default_json_Paramsconfigs',
            field=models.CharField(blank=True, db_column='jsonStringParams', max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='pretrainpath',
            field=models.CharField(blank=True, db_column='pretrainpath', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='modelsoftlibid',
            field=models.IntegerField(blank=True, db_column='modelSoftLibID', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='modeltype',
            field=models.ForeignKey(blank=True, db_column='datasetType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.typepermission'),
        ),
    ]
