# Generated by Django 3.2.2 on 2022-12-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0011_auto_20221207_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='modelsoftlibid',
            field=models.IntegerField(blank=True, db_column='modelSoftLibID', null=True),
        ),
    ]
